"use strict";

module.exports = {
  rules: {
    "require-author": "error",
    "require-bugs": "error",
    "require-description": "error",
    "require-homepage": "error",
    "require-keywords": "error",
    "require-license": "error",
    "require-name": "error",
    "require-repository": "error",
    "require-version": "error",
    "bin-type": "error",
    "bundledDependencies-type": "error",
    "config-type": "error",
    "cpu-type": "error",
    "description-type": "error",
    "dependencies-type": "error",
    "devDependencies-type": "error",
    "directories-type": "error",
    "engines-type": "error",
    "files-type": "error",
    "homepage-type": "error",
    "keywords-type": "error",
    "license-type": "error",
    "main-type": "error",
    "man-type": "error",
    "name-type": "error",
    "optionalDependencies-type": "error",
    "os-type": "error",
    "peerDependencies-type": "error",
    "preferGlobal-type": "error",
    "private-type": "error",
    "repository-type": "error",
    "scripts-type": "error",
    "version-type": "error",
    "prefer-caret-version-dependencies": "error",
    "prefer-alphabetical-dependencies": "error",
    "prefer-caret-version-devDependencies": "error",
    "prefer-alphabetical-devDependencies": "error",
    "prefer-alphabetical-optionalDependencies": "error",
    "prefer-alphabetical-peerDependencies": "error",
    "name-format": "error",
    "version-format": "error",
    "prefer-property-order": ["error", [
      "name",
      "version",
      "private",
      "description",
      "keywords",
      "homepage",
      "repository",
      "bugs",
      "author",
      "contributors",
      "license",
      "files",
      "main",
      "module",
      "jsnext:main",
      "types",
      "typings",
      "style",
      "example",
      "examplestyle",
      "assets",
      "bin",
      "man",
      "directories",
      "browser",
      "browserify",
      "babel",
      "eslintConfig",
      "stylelint",
      "npmPackageJsonLintConfig",
      "dependencies",
      "devDependencies",
      "peerDependencies",
      "bundledDependencies",
      "bundleDependencies",
      "optionalDependencies",
      "engines",
      "engineStrict",
      "os",
      "cpu",
      "preferGlobal",
      "scripts",
      "pre-commit",
      "config",
      "publishConfig",
    ]],
  },
};
